サインアップ編集
king58-1224/bbscore pull request #12
Opened 2020-10-13 11:46 UTC by shirarinix

一通りビューも実装したので確認お願いします。
コード部分でおかしな記述があれば指摘お願いします。

見た目はフリマを参考に作成しました。

2020-10-15 02:30 UTC, tsuyatsuya-april requested changes

2020-10-15 02:30 UTC, tsuyatsuya-april commented on app/views/devise/registrations/new.html.erb
> +    <label class="form-text">チーム名（必須）</label><br />
チーム名(必須)をパスワード確認（必須）に変更お願いします。

2020-10-16 09:24 UTC, shirarinix commented
・指摘部分の修正を実施しました。
・また、サインアップ、ログインを表示しないようにコメントアウトしています。
　私的には必要ないかと思います。
変更前→https://gyazo.com/54122cac5db726e643f55878425c1f47
変更後→https://gyazo.com/a242abf834b83fdfb7bfbe84562d1f47

2020-10-16 09:36 UTC, shirarinix commented
・ログインボタンのレイアウト（見た目）変更し忘れてたので編集し直してます

2020-10-16 10:28 UTC, merged